module.exports = {
	dest: 'build/development',
	dest_release: 'build/release',
	html: 'index.html',
	xscripts: [
		'app/*.jsx', 
		'app/**/*.jsx'
		],
	scripts: [ // replace it with xscripts later
		'js/bootstrap.js',
		'app/parts/Billet.js',
		'app/parts/Workplace.js',
		'app/scratches.js',
		'app/knowledge.js',
		'app/draw.js',
		'app/space/Ship.js',
		'app/space/Space.js',
		'app/rally/Rally.js',
		'app/castle/Castle.js',
		'app/dungeon/Dungeon.js',
		'app/dungeon/Unit.js',
		'app/Gatherer.js',
		'app/Building.js',
		'app/Civilization.js',
		'app/Department.js',
		'app/Player.js',
		'app/Storages.js',
		'app/skills.js',
		'app/Badge.js',
		'app/badges.db.js',
		'app/Startup.js',
		'app/startups.db.js',
		'app/Objective.js',
		'app/objectives.db.js',
		'app/Action.js',
		'app/actions.db.js',
		'app/Event.js',
		'app/events.db.js',
		'app/Lecture.js',
		'app/lectures.db.js',
		'app/LogPanel.js',
		'app/tips.js',
		'app/time.jsx',
		'app/main.jsx'
	],
	styles: ['css/*.css'],
}
